# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "login": "Keks",
  "password": "123456",
  "avatar": "/images/user.png"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/669b833d176cd8a2e1a66ffe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjliODMzZDE3NmNkOGEyZTFhNjZmZmUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsb2dpbiI6Iktla3MiLCJpYXQiOjE3MjMwMDkyNzMsImV4cCI6MTcyMzAwOTU3M30.0gBcd8PHb2KsYSU1xZiKAgETLaS_hY5SExIJZW75TZc

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjliODMzZDE3NmNkOGEyZTFhNjZmZmUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsb2dpbiI6Iktla3MiLCJpYXQiOjE3MjM0NjU3MzUsImV4cCI6MTcyNjA1NzczNX0.fACcRBSaTEWtqC8YUnh8782yYvl7GqzujgIuD3UQ0iI

###

# Check user token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjliODMzZDE3NmNkOGEyZTFhNjZmZmUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJsb2dpbiI6Iktla3MiLCJpYXQiOjE3MjM2MjA1NTEsImV4cCI6MTcyMzYyMDg1MX0.r6nXoumhCzlbDq6ZzhUsoOvgS6QaqZUM2oO8V9-SPKc

###
